name: Logsmith Changelog
description: Generate changelogs and create GitHub releases using logsmith
author: Stacks.js
branding:
  icon: file-text
  color: blue

inputs:
  token:
    description: GitHub token for creating releases and committing files
    required: true
  generate-changelog:
    description: Whether to generate a full changelog file
    required: false
    default: 'true'
  changelog-file:
    description: Path to the changelog file
    required: false
    default: CHANGELOG.md
  create-release:
    description: Whether to create a GitHub release
    required: false
    default: 'false'
  release-tag:
    description: Git tag for the release (auto-detected from context if not provided)
    required: false
    default: ''
  release-title:
    description: Title for the GitHub release
    required: false
    default: ''
  release-draft:
    description: Whether to create the release as a draft
    required: false
    default: 'false'
  release-prerelease:
    description: Whether to mark the release as a prerelease
    required: false
    default: 'false'
  commit-changelog:
    description: Whether to commit the generated changelog
    required: false
    default: 'false'
  theme:
    description: Theme to use for changelog generation
    required: false
    default: github
  format:
    description: Output format for changelog (markdown, json, html)
    required: false
    default: markdown
  from:
    description: Starting commit/tag for changelog range
    required: false
    default: ''
  to:
    description: Ending commit/tag for changelog range
    required: false
    default: HEAD
  config-path:
    description: Path to logsmith config file
    required: false
    default: ''
  working-directory:
    description: Working directory for the action
    required: false
    default: .
  verbose:
    description: Enable verbose logging
    required: false
    default: 'false'

outputs:
  changelog-content:
    description: Generated changelog content
  changelog-path:
    description: Path to the generated changelog file
  release-id:
    description: ID of the created GitHub release
  release-url:
    description: URL of the created GitHub release
  release-upload-url:
    description: Upload URL for the created GitHub release
  commit-sha:
    description: SHA of the commit if changelog was committed

runs:
  using: node20
  main: dist/index.js
